### PR TITLE
Updated important things

### PR DESCRIPTION
**Pull request by ttodua**
Per https://wordpress.org/support/topic/some-errors-22/

I've addresses all listed 10 fixes. 

-1
-2
-3 remains as question, I havent addressed to that
-4 - addressed to avoid  `.` or `+` part manipulations from email
-5 - this should be disregarded for now, i think we don't need that
-6 
-7
-8
-9  I havent tested your plugin before this, however 4th one will fix this too.
-10

### CODE REVIEW

**Comment by ttodua** [comment]
fixed the above things:
#1
#2
#3 remains as question, I havent addressed to that
#4 - addressed to avoid  `.` or `+` part manipulations from email
#5 - this should be disregarded for now, i think we don't need that
#6 
#7
#8
#9  I havent tested your plugin against that, instead #4 will fix this too.

**Comment by tarecord** [comment]
@ttodua Thanks for all your thought and work on this!

Can you split up this PR into each of your proposed changes so we can review each one? I can see the discussion in this one PR getting quite complicated if there is a lot to discuss.

**Comment by ttodua** [comment]
> @ttodua Thanks for all your thought and work on this!
> 
> Can you split up this PR into each of your proposed changes so we can review each one? I can see the discussion in this one PR getting quite complicated if there is a lot to discuss.

tarecord, I am sorry, I am not a guru of github and couldnt find out how to split already PR-ed request in parts..
It would have been excellent if you could review the mentioned link of wordpress.org forum, where I have numbered the list of issues with i.e. `1)`, `2)`, ... etc and it might be easy to look through them and let me know here if you have any questions, I tried to be clear when explaining, so, would be excellent if your plugin considers the suggested updates.

**Comment by tarecord** [comment]
What I meant by that is to submit additional PRs, each addressing an isolated issue or feature. Then we can talk about each individually instead of grouping together in one giant pull-request.

**Comment by ttodua** [comment]
well, yes, i couldnt figure out how to split the PR into individual ones. As I mentioned, I am not well-versed in GitHub and couldnt find how to do what you say.
anyway, i dont think it might be too large PR request to analyze.

**Comment by tarecord** [comment]
Hey @ttodua since I've addressed most of what's in this PR, I'm going to close it out.

**Comment by ttodua** [comment]
thanks, nice work! I will check it whenever i can.

**Comment by ttodua** [comment]
I've checked and actually, when i numbered issues in the top post by `1,2,3,4.....` only some part of them seem to be implemented. Well, good luck anyway.

**Pull request closed without merging**
